# SPDX-FileCopyrightText: 2025 Jo√£o V. Farias (beyondmagic) <beyondmagic@mail.ru>
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
    postgres:
        image: postgres:latest
        container_name: digital_garden_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            TZ: ${TZ}
        ports:
            - "5432:5432"
        volumes:
            - digital_garden_data:/var/lib/postgresql

volumes:
    digital_garden_data: